### PR TITLE
fix(api): update export so that importing the api is more natural

### LINKED ISSUE #122: rtirl-obs/api Module not found: Error
Module not found: Error: Package path . is not exported from package node_modules\@rtirl\api (see exports field in node_modules\@rtirl\api\package.json)  

Resolve by editing package.json exports as follows:
```
  "exports": {
    ".": "./lib"
  },
  ```

### PR DESCRIPTION
**Pull request by juaoose**
Closes #122 

I believe this would classify for a major version change right? Since it should break old imports

### CODE REVIEW

**Comment by kevmo314** [comment]
Does it actually break old imports? I thought this just made it so `import RealtimeIRL from '@rtirl/api';` worked?

**Comment by juaoose** [comment]
It does, I guess because the export is no longer a directory, `from '@rtirl/api/.'` should fail.

**Comment by kevmo314** [comment]
> Yeah `./.` is not exported anymore so `import RealtimeIRL from '@rtirl/api/.';` will fail

I think that's ok, it would be strange for someone to import it that way, but just to make sure:

`import RealtimeIRL from '@rtirl/api';` works but didn't previously
`import * as RealtimeIRL from '@rtirl/api';` still works?

If so I don't think this is a breaking change. `import RealtimeIRL from `@rtirl/api/.';` wasn't intended to be supported anyways.

**Review by kevmo314 — APPROVED** [review]

**Comment by juaoose** [comment]
> > Yeah `./.` is not exported anymore so `import RealtimeIRL from '@rtirl/api/.';` will fail
> 
> I think that's ok, it would be strange for someone to import it that way, but just to make sure:
> 
> `import RealtimeIRL from '@rtirl/api';` works but didn't previously `import * as RealtimeIRL from '@rtirl/api';` still works?
> 
> If so I don't think this is a breaking change. `import RealtimeIRL from `@rtirl/api/.';` wasn't intended to be supported anyways.

- `import RealtimeIRL from '@rtirl/api';` this one doesn't work because we don't have a default export, I think.
- `import * as RealtimeIRL from '@rtirl/api'` starts working with this change.

**Comment by kevmo314** [comment]
Ok yeah we can minor version bump this and release 👍

**Pull request merged**
